version: 2.1

orbs:
  node: circleci/node@3.0.0

workflows:
  main:
    jobs:
      - node/test
      - deploy:
          filters:
            branches:
              ignore:
                - master

jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - run:
          name: Deploy Vercel production
          command: npx vercel --prod --token $VERCEL_TOKEN
